<script lang="ts">
	import Icon from '../ui/Icon.svelte';
	let { kind = 'software-development' }: { kind?: string } = $props();
</script>

<div class="artwork" class:advertising={kind === 'digital-advertising'} class:property={kind === 'real-estate-services'} aria-hidden="true">
	<div class="dot-grid"></div>
	{#if kind === 'digital-advertising'}
		<div class="signal-ring ring-a"></div><div class="signal-ring ring-b"></div><div class="signal-ring ring-c"></div>
		<div class="signal-center"><Icon name="megaphone" size={64} stroke={1.2} /></div>
		<span class="satellite sat-one"><Icon name="users" size={22} /></span><span class="satellite sat-two"><Icon name="globe" size={25} /></span><span class="satellite sat-three"><Icon name="star" size={20} /></span>
		<div class="creative-tile"><span class="creative-sun"></span><span class="creative-line"></span><span class="creative-line short"></span><span class="creative-button"><Icon name="arrow-up-right" size={14} /></span></div>
	{:else if kind === 'software-development' || kind === 'web-solutions'}
		<div class="app-window" class:web={kind === 'web-solutions'}><div class="window-top"><span></span><span></span><span></span><i></i></div><div class="window-content"><div class="app-sidebar"><b></b><i></i><i></i><i></i><i></i></div><div class="app-main"><div class="app-title"></div><div class="app-cards"><span><Icon name="chart" size={22} /></span><span><Icon name="users" size={22} /></span><span><Icon name="layers" size={22} /></span></div><div class="app-chart"><i></i><i></i><i></i><i></i><i></i><i></i><i></i></div></div></div></div>
		<span class="floating-code"><Icon name={kind === 'web-solutions' ? 'globe' : 'code'} size={32} /></span>
		{#if kind === 'web-solutions'}<div class="mini-phone"><span></span><b></b><i></i><i></i><i></i></div>{:else}<div class="code-strip"><span></span><span></span><span></span></div>{/if}
	{:else if kind === 'digital-consultancy'}
		<svg class="route" viewBox="0 0 500 220"><path d="M45 170 H150 Q180 170 180 140 V105 Q180 75 210 75 H290 Q320 75 320 105 V120 Q320 150 350 150 H455" fill="none" stroke="currentColor" stroke-width="2" stroke-dasharray="6 6"/></svg><span class="route-node start"><Icon name="search" size={25} /></span><span class="route-node middle"><Icon name="target" size={30} /></span><span class="route-node finish"><Icon name="arrow-up-right" size={25} /></span>
	{:else if kind === 'real-estate-services'}
		<div class="skyline"><div class="building small"><span></span><span></span><span></span><span></span></div><div class="building tall"><span></span><span></span><span></span><span></span><span></span><span></span></div><div class="building medium"><span></span><span></span><span></span><span></span></div></div><span class="property-pin"><Icon name="pin" size={35} /></span><div class="ground-line"></div>
	{:else if kind === 'digital-currency-operations'}
		<div class="currency-orbit"></div><div class="currency-orbit second"></div><span class="currency-coin"><Icon name="coin" size={57} stroke={1.2} /></span><span class="currency-node"><Icon name="layers" size={24} /></span><span class="currency-dot"></span>
	{:else}
		<div class="info-stack back"></div><div class="info-stack front"><span class="info-title"></span><div class="info-row"><i></i><b></b></div><div class="info-row"><i></i><b></b></div><div class="info-row"><i></i><b></b></div></div><span class="info-badge"><Icon name="info" size={30} /></span>
	{/if}
</div>

<style>
	.artwork { position: relative; height: 240px; min-width: 0; isolation: isolate; overflow: hidden; background: radial-gradient(ellipse at 85% 0%, #ffbd5820, transparent 65%), #142a40; color: #ffbd58; }
	.dot-grid { position: absolute; inset: 0; background-image: radial-gradient(#afc1d133 1px, transparent 1px); background-size: 18px 18px; mask-image: linear-gradient(90deg, transparent, #000); }
	.advertising { height: 100%; min-height: 360px; background: radial-gradient(ellipse at center, #ffbd5817, transparent 70%), #142a40; }
	.signal-ring { position: absolute; top: 50%; left: 50%; translate: -50% -50%; border: 1px solid #ffbd5833; border-radius: 50%; aspect-ratio: 1; }
	.ring-a { width: 180px; }.ring-b { width: 290px; }.ring-c { width: 410px; }
	.signal-center { position: absolute; top: 50%; left: 50%; translate: -50% -50%; width: 118px; height: 118px; display: grid; place-items: center; border-radius: 30px; background: #ffbd58; color: #12263d; box-shadow: 0 16px 50px #0004; transform: rotate(-10deg); }
	.satellite { position: absolute; display: grid; place-items: center; width: 50px; height: 50px; border: 1px solid #60748b; border-radius: 15px; background: #203950; }
	.sat-one { top: 16%; left: 26%; }.sat-two { bottom: 14%; left: 29%; }.sat-three { top: 29%; right: 15%; }
	.creative-tile { position: absolute; width: 108px; height: 125px; right: 10%; bottom: 12%; border: 1px solid #6f7c84; background: #284156; border-radius: 14px; padding: 12px; transform: rotate(12deg); }
	.creative-sun { display: block; width: 100%; height: 48px; background: radial-gradient(circle at 70% 45%, #ffbd58 14px, transparent 15px), linear-gradient(145deg,#627687,#344d61); border-radius: 6px; }
	.creative-line { display: block; width: 70%; height: 3px; background: #b6c9d7; margin-top: 10px; }.creative-line.short { width: 45%; margin-top: 5px; }.creative-button { display: grid; place-items: center; background: #ffbd58; color: #12263d; width: 24px; height: 24px; border-radius: 50%; position: absolute; right: 12px; bottom: 10px; }
	.app-window { width: 63%; height: 181px; position: absolute; left: 18%; top: 32px; border: 1px solid #60758a; border-radius: 12px; background: #1b344b; transform: rotate(-5deg); box-shadow: 0 15px 40px #06132066; overflow: hidden; }
	.window-top { height: 25px; display: flex; align-items: center; gap: 4px; padding: 0 10px; border-bottom: 1px solid #435b70; }
	.window-top span { height: 4px; width: 4px; border-radius: 50%; background: #73879b; }.window-top span:first-child { background: #ffbd58; }.window-top i { margin-left: auto; width: 35%; height: 4px; background: #435b70; border-radius: 3px; }
	.window-content { display: flex; height: 155px; }.app-sidebar { width: 20%; padding: 14px 10px; border-right: 1px solid #435b70; }.app-sidebar b { display: block; height: 12px; width: 12px; background: #ffbd58; border-radius: 3px; margin-bottom: 15px; }.app-sidebar i { display: block; background: #60798d; height: 4px; margin-bottom: 10px; }
	.app-main { flex: 1; min-width: 0; padding: 14px; }.app-title { width: 45%; height: 5px; background: #c3d4de; border-radius: 5px; margin-bottom: 12px; }.app-cards { display: grid; grid-template-columns: repeat(3,1fr); gap: 7px; }.app-cards > span { padding: 8px; background: #2b475f; border-radius: 5px; }.app-chart { display: flex; align-items: flex-end; gap: 8%; height: 55px; padding-top: 10px; border-bottom: 1px solid #647c90; }.app-chart i { width: 9%; background: #7d95a9; border-radius: 2px 2px 0 0; height: 35%; }.app-chart i:nth-child(2n) { height: 65%; }.app-chart i:nth-child(3n) { height: 50%; }.app-chart i:last-child { height: 95%; background: #ffbd58; }
	.floating-code { position: absolute; top: 29px; right: 10%; padding: 12px; border-radius: 15px; background: #ffbd58; color: #12263d; transform: rotate(8deg); box-shadow: 0 10px 25px #0003; }.code-strip { position: absolute; left: 9%; bottom: 27px; padding: 15px; background: #254158; border: 1px solid #567084; border-radius: 10px; width: 115px; transform: rotate(5deg); }.code-strip span { display: block; height: 4px; background: #ffbd58; margin-bottom: 6px; width: 55%; }.code-strip span:nth-child(2) { width: 85%; background: #8eaabd; }.code-strip span:last-child { width: 35%; margin: 0; }
	.web { transform: rotate(3deg); left: 16%; }.mini-phone { position: absolute; width: 62px; height: 112px; right: 14%; bottom: 10px; border: 3px solid #738698; border-radius: 12px; background: #12263d; transform: rotate(-8deg); padding: 8px; }.mini-phone span { display: block; margin: 0 auto 10px; width: 20px; height: 3px; border-radius: 5px; background: #9bb0c2; }.mini-phone b { display: block; height: 28px; background: #ffbd58; border-radius: 4px; margin-bottom: 8px; }.mini-phone i { display: block; height: 4px; margin-top: 5px; background: #718ca2; border-radius: 2px; }
	.route { position: absolute; inset: 0; width: 100%; height: 100%; opacity: .6; }.route-node { position: absolute; display: grid; place-items: center; width: 62px; height: 62px; border: 1px solid #6b8191; border-radius: 18px; background: #264158; }.route-node.start { left: 12%; top: 56%; }.route-node.middle { left: 45%; top: 21%; background: #ffbd58; color: #12263d; transform: rotate(10deg); }.route-node.finish { right: 8%; top: 47%; }
	.skyline { display: flex; align-items: flex-end; gap: 12px; position: absolute; bottom: 33px; left: 23%; }.building { display: grid; grid-template-columns: repeat(2,1fr); padding: 15px; gap: 10px; width: 65px; background: #304d63; border: 1px solid #7690a3; border-radius: 6px 6px 0 0; }.building span { background: #8098a9; width: 10px; height: 14px; }.building.tall { height: 150px; background: #385a73; }.building.small { height: 90px; }.building.medium { height: 115px; }.building.tall span:nth-child(2n) { background: #ffbd58; }.property-pin { position: absolute; right: 17%; top: 30px; color: #ffbd58; }.ground-line { position: absolute; bottom: 32px; left: 15%; right: 15%; height: 1px; background: #97aaba; }
	.currency-orbit { position: absolute; width: 265px; height: 145px; border: 1px solid #9caebe66; border-radius: 50%; left: 50%; top: 50%; transform: translate(-50%,-50%) rotate(-25deg); }.currency-orbit.second { transform: translate(-50%,-50%) rotate(25deg); }.currency-coin { position: absolute; display: grid; place-items: center; width: 95px; height: 95px; left: 50%; top: 50%; translate: -50% -50%; border: 1px solid #ffbd58; border-radius: 50%; background: #294153; }.currency-node { position: absolute; left: 20%; bottom: 30px; border: 1px solid #8297a6; border-radius: 12px; background: #294153; padding: 10px; }.currency-dot { position: absolute; width: 13px; height: 13px; border: 3px solid #5d5f51; border-radius: 50%; background: #ffbd58; right: 20%; top: 47px; }
	.info-stack { position: absolute; width: 200px; height: 145px; left: 50%; top: 50%; border: 1px solid #7790a3; border-radius: 14px; background: #1f3a50; }.info-stack.back { transform: translate(-60%,-45%) rotate(-12deg); opacity: .65; }.info-stack.front { transform: translate(-40%,-50%) rotate(6deg); padding: 23px; }.info-title { display: block; width: 60%; height: 6px; border-radius: 4px; background: #ffbd58; margin-bottom: 20px; }.info-row { display: flex; gap: 10px; align-items: center; margin-bottom: 10px; }.info-row i { height: 10px; width: 10px; background: #819cb0; border-radius: 3px; }.info-row b { width: 75%; height: 4px; background: #648298; border-radius: 2px; }.info-row:last-child b { width: 45%; }.info-badge { position: absolute; top: 25px; left: 22%; color: #12263d; padding: 10px; background: #ffbd58; border-radius: 50%; }
	@media(max-width:480px) { .artwork { height: 210px; }.advertising { min-height: 280px; }.signal-center { width: 92px; height: 92px; }.ring-c { width: 310px; }.ring-b { width: 230px; }.ring-a { width: 140px; }.creative-tile { width: 83px; height: 105px; right: 6%; bottom: 8%; }.creative-sun { height: 35px; }.sat-one { left: 18%; top: 9%; }.sat-two { left: 15%; }.sat-three { right: 9%; top: 17%; }.app-window { width: 76%; left: 12%; top: 20px; height: 168px; }.app-main { padding: 10px; }.floating-code { top: 10px; right: 6%; padding: 9px; }.code-strip { left: 5%; bottom: 12px; padding: 10px; width: 90px; }.app-chart { height: 47px; }.skyline { left: 15%; gap: 9px; }.building { width: 55px; padding: 12px; gap: 7px; }.property-pin { right: 8%; }.info-stack { width: 175px; }.info-badge { left: 10%; }.currency-node { left: 10%; }.currency-dot { right: 9%; }.route-node { width: 48px; height: 48px; border-radius: 13px; } }
</style>
